export default Object.freeze({
  COMMAND_RELATION: {
    undo: {
      cmd: "undo",
      text: "실행취소",
      icon: "undo",
      desc: "실행취소",
    },
    redo: {
      cmd: "redo",
      text: "다시실행",
      icon: "repeat",
      desc: "다시실행",
    },
    justifyFull: {
      cmd: "justifyFull",
      text: "양쪽정렬",
      icon: "align-justify",
      desc: "양쪽정렬",
    },
    justifyLeft: {
      cmd: "justifyLeft",
      text: "왼쪽정렬",
      icon: "align-left",
      desc: "왼쪽정렬",
    },
    justifyCenter: {
      cmd: "justifyCenter",
      text: "중앙정렬",
      icon: "align-center",
      desc: "중앙정렬",
    },
    justifyRight: {
      cmd: "justifyRight",
      text: "오른정렬",
      icon: "align-right",
      desc: "오른정렬",
    },
    indent: {
      cmd: "indent",
      text: "들여쓰기",
      icon: "indent",
      desc: "들여쓰기",
    },
    outdent: {
      cmd: "outdent",
      text: "내어쓰기",
      icon: "outdent",
      desc: "내어쓰기",
    },
    bold: {
      cmd: "bold",
      text: "굵게",
      icon: "bold",
      desc: "굵게",
    },
    italic: {
      cmd: "italic",
      text: "기울임",
      icon: "italic",
      desc: "기울임",
    },
    strikeThrough: {
      cmd: "strikeThrough",
      text: "취소선",
      icon: "strikethrough",
      desc: "취소선",
    },
    underline: {
      cmd: "underline",
      text: "밑줄",
      icon: "underline",
      desc: "밑줄",
    },
    insertOrderedList: {
      cmd: "insertOrderedList",
      text: "insertOrderedList",
      icon: "list-ol",
      desc:
        "Creates a numbered ordered list for the selection or at the insertion point.",
    },
    insertUnorderedList: {
      cmd: "insertUnorderedList",
      text: "insertUnorderedList",
      icon: "list-ul",
      desc:
        "Creates a bulleted unordered list for the selection or at the insertion point.",
    },
    insertParagraph: {
      cmd: "insertParagraph",
      text: "insertParagraph",
      icon: "paragraph",
      desc:
        "Inserts a paragraph around the selection or the current line. (Internet Explorer inserts a paragraph at the insertion point and deletes the selection.)",
    },
    subscript: {
      cmd: "subscript",
      text: "subscript",
      icon: "subscript",
      desc:
        "Toggles subscript on/off for the selection or at the insertion point.",
    },
    superscript: {
      cmd: "superscript",
      text: "superscript",
      icon: "superscript",
      desc:
        "Toggles superscript on/off for the selection or at the insertion point.",
    },
    createLink: {
      cmd: "createLink",
      text: "createLink",
      val: "https://twitter.com/netsi1964",
      icon: "link",
      desc:
        "Creates an anchor link from the selection, only if there is a selection.This requires the HREF URI string to be passed in as a value argument.The URI must contain at least a single character, which may be a white space. (Internet Explorer will create a link with a null URI value.)",
    },
    unlink: {
      cmd: "unlink",
      text: "unlink",
      icon: "chain-broken",
      desc: "Removes the anchor tag from a selected anchor link.",
    },
  },
  LIST_FONT_SIZE: [10, 12, 14, 16, 20, 22, 30, 35, 40, 45, 50],


  LIST_FONT_FAMILY: [
    "Agency FB",
    "Albertina",
    "Antiqua",
    "Architect",
    "Arial",
    "BankFuturistic",
    "BankGothic",
    "Blackletter",
    "Blagovest",
    "Calibri",
    "Comic Sans MS",
    "Consolas",
    "Courier",
    "Cursive",
    "Decorative",
    "Fantasy",
    "Fraktur",
    "Frosty",
    "Garamond",
    "Georgia",
    "Helvetica",
    "Impact",
    "Minion",
    "Modern",
    "Monospace",
    "Open Sans",
    "Palatino",
    "Perpetua",
    "Roman",
    "Sans-serif",
    "Serif",
    "Script",
    "Swiss",
    "Tahoma",
    "Times",
    "Times New Roman",
    "Tw Cen MT",
    "Verdana",
  ],
});